import { AgentSkill } from "./types";

export const AGENT_SKILLS: AgentSkill[] = [
  {
    id: "web-deep-search",
    name: "Web Intelligence & Scraping",
    category: "research",
    description: "Fetch, strip HTML, and summarize real-time web content, documentation, or online articles.",
    prompt: "Fetch and summarize the key technical concepts from https://news.ycombinator.com",
    icon: "Globe",
    agentRole: "research",
    badge: "Live Web",
  },
  {
    id: "python-sandbox",
    name: "Python Compute Sandbox",
    category: "code",
    description: "Safely execute Python algorithms, data structures, math, and simulations with instant output.",
    prompt: "Run Python to calculate monthly amortization and total interest on a $350,000 30-year mortgage at 6.5%.",
    icon: "Code2",
    agentRole: "code",
    badge: "Python 3.12",
  },
  {
    id: "tabular-data-analytics",
    name: "CSV & Tabular Analytics",
    category: "data",
    description: "Analyze datasets, calculate column summary statistics, distributions, and discover data anomalies.",
    prompt: "Analyze this dataset structure: Year,Revenue,Profit,Growth\n2021,100,20,15%\n2022,140,28,40%\n2023,190,42,35%\n2024,260,65,37%",
    icon: "BarChart3",
    agentRole: "data",
    badge: "Profiling",
  },
  {
    id: "doc-rag-synthesis",
    name: "Document Semantic Extraction",
    category: "analysis",
    description: "Query indexed PDFs, DOCX, and notes using vector search and retrieval-augmented generation.",
    prompt: "What are the primary conclusions, risks, and action items highlighted across my uploaded document?",
    icon: "FileSearch",
    agentRole: "docs",
    badge: "Vector RAG",
  },
  {
    id: "live-clock-temporal",
    name: "Temporal & Date Grounding",
    category: "automation",
    description: "Query exact real-time calendar dates, elapsed business days, and timezones globally.",
    prompt: "What is the exact current date, time in UTC, and how many days remain until the end of the current quarter?",
    icon: "Clock",
    agentRole: "auto",
    badge: "Real-time",
  },
  {
    id: "multi-agent-swarm",
    name: "Ruflo Multi-Agent Swarm",
    category: "automation",
    description: "Coordinate specialized agents (researcher, coder, reviewer) in parallel to solve complex tasks.",
    prompt: "Decompose a multi-tier SaaS architecture with authentication, Redis caching, and async task queues.",
    icon: "Network",
    agentRole: "auto",
    badge: "Swarm",
  },
  {
    id: "api-schema-builder",
    name: "API & Payload Architect",
    category: "code",
    description: "Generate production-grade OpenAPI specifications, JSON schemas, and test curl queries.",
    prompt: "Draft a clean RESTful OpenAPI 3.1 schema for an agent task queue with status webhooks and polling.",
    icon: "Cpu",
    agentRole: "code",
    badge: "OpenAPI",
  },
  {
    id: "stock-market-pulse",
    name: "Market & Financial Quotes",
    category: "data",
    description: "Retrieve stock ticker metrics, performance overviews, and financial health profiles.",
    prompt: "Analyze recent market performance and key valuation multiples for NVDA, MSFT, and GOOGL.",
    icon: "TrendingUp",
    agentRole: "data",
    badge: "Finance",
  },
];
